
# MQTT服务器
broker = "tcp://192.168.1.123:1883"

# 用户名
username = "test"

# 密码
password = "test123"

# 客户端ID
client_id = "go-server-"

# 共享订阅前缀
share_prefix = "$share/go/"

# 是否分布式部署（随机客户端ID）
distributed = false